### PR TITLE
Live Scanner Location & POI/webhook & Maptile updates from Stock

### PR DESCRIPTION
**Pull request by SenorKarlos**
Tested and working on my server, screenshot: http://prntscr.com/rmc931
Although you don't particualrly need it, I would like to stay on your branch if you merge it :D

### CODE REVIEW

**Comment by SenorKarlos** [comment]
I got bored and was very pleased with my success so far, so I updated the POI functions. The only thing that isn't proper is the delete button and various other label icons appear as empty boxes. I am also modifying the tampermonkey Wayfarer script for PMSF POI table use which was the other motivation for going one step further

**Comment by SenorKarlos** [comment]
I fixed everything in my DM to you except for the Google Streets "for Development Only" issue and added the mapbox settings & styles so users can play with the PoGo syle

**Comment by SenorKarlos** [comment]
After working with the tampermonkey exporter script, talking to folks, and doing some submissions myself, I've noticed that the 'resubmit' & 'ineligible' statuses were redundant and the whole system could use some naming updates. I'm not sure if Operation portal recon had resubmitting, but in Wayfarer once it's dead it's dead. 

This is also meant to be primarly used with my updated importer script at https://github.com/SenorKarlos/wayfarer-PMSF-export and a stopwatcher based py script (next step) to clean up things like duplicates, resubmissions (keep newest within radius, submissions within 20m of a portal, accepted removals, etc. The manual submit messages and webhooks have also been updated so manual use is better as well, and sub 40 players can still mark spots they can't send in yet for others to pick up, or for level 40's to track things they have no submission room for yet

- The Options section in the sidebar is now called Wayfarer & Weather
- POI switch called Waystops
- Submit menu icon the ! with a circle in it
- Everything POI given Wayspot related names
- Status 1 for candidates, 2 for submitted/voting, 3 for declined (for whatever reason)
- Added submitted timestamp to DB & field to POI label to use and track original submission date that comes from wayfarer export, and use updated for last status update dates going foward

I would like to update the 'dot' being used to different colored exclamations and allow for image link entry (with or without a check for googleusercontent in url) while keeping file upload option but beyond my scope at the moment. Possibly in a future patch or with some assistance.

I still need to make some of the button & label icons work with your fork but wanted to capture the changes up to here to make a PR to stock anyways and with all that lint & whitespace cleaning it was time.

**Comment by SenorKarlos** [comment]
http://prntscr.com/rr31dk New Sidebar labels
http://prntscr.com/rr20n6 Submit new - needs scroll bar or bigger frame
http://prntscr.com/rr21s1 Manual submit webhook (username works, just too many close together so I've been skoodated)
http://prntscr.com/rr23j9 Have to refresh to see new POI
http://prntscr.com/rr25a2 Editing - has scroll bar on large image, not sure how to replicate in 1st
http://prntscr.com/rr26bz Conf dialog good
http://prntscr.com/rr2krg had some issues due to a typo, fixed, and edited twice (same image & re-upload image) to get those webhooks although I can't figure out why the one with no image upload didn't trigger thumbnail & image. The code is written to send the same webhook no matter what happened above if discord channel url set, as long as it happened.
http://prntscr.com/rr2qti had to refresh again for changes (during webhook bug and after) testing mark functions
http://prntscr.com/rr2s46 prompt good
http://prntscr.com/rr2swa webhook for submitted
http://prntscr.com/rr2u5e had to refresh, dot green, hitting decline & OK
http://prntscr.com/rr2v6b decline webhook
http://prntscr.com/rr2ycm you guessed it still refreshing LOL about to delete
http://prntscr.com/rr2z54 finally it auto-refreshes! but takes the other POI with it and they only come back by flicking switch or refreshing
http://prntscr.com/rr3018 and lastly delete webhook.

Everything updated in wording & function to match with Wayfarer's statuses and wordings, and tested functional. I also employed a get poi_id and while check if the randomnum exists before creating a new POI, to avoid the infinitesimal chance of a user submission getting errored out. I believe the refreshing issue with POI exists in stock, as well as the flickering devices, but this is now ready except for helping me make those missing label icons appear :D

Also gave the files one more once-over for spacing/tabs, lint doesn't seem to care how you format PHP files as long as they're valid it seems

**Comment by xxleevo** [comment]
We texted about this.. Gonna wait for the next MR ;)

**Pull request closed without merging**
